# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_auto_20171122_2140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='DVD',
        ),
        migrations.RemoveField(
            model_name='song',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
