# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editor', '0006_auto_20171122_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('segments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Segment')),
            ],
        ),
        migrations.AddField(
            model_name='balancesheetitem',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Segment'),
        ),
    ]
