# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_auto_20171122_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheetitem',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.Segment'),
        ),
    ]
