# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_auto_20171122_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='segments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.Segment'),
        ),
    ]
