# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_auto_20171122_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesheetitem',
            old_name='segment',
            new_name='parent_segment',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='segments',
        ),
        migrations.AddField(
            model_name='segment',
            name='parent_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.Segment', verbose_name='parent segment'),
        ),
    ]
