# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_auto_20171123_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='logic_segment',
            field=models.TextField(blank=True),
        ),
    ]
