# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0012_election'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='segments',
        ),
        migrations.AddField(
            model_name='segment',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.Election'),
        ),
    ]
