# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0013_auto_20171123_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheetitem',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='election',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
